### ISSUE TITLE
Can I buy these somewhere?

### ISSUE THREAD

**Issue by jthoward64** [mkrl/misbrands#3]
The readme doesn't seem to say anything about it, are these just for printing/using or is there a storefront somewhere that I can buy one of these?

**Comment by mkrl** [comment]
Feel free to print those out / use the images in any way you want.

I've released the repo under a CC license https://github.com/mkrl/misbrands/pull/4

**Comment by nuke-web3** [comment]
I like https://www.stickergiant.com/coupons a lot 😁

**Comment by jthoward64** [comment]
> Feel free to print those out / use the images in any way you want.
> 
> 
> 
> I've released the repo under a CC license https://github.com/mkrl/misbrands/pull/4

Alright, thanks for the reply!
