### ISSUE TITLE
Is ruby on rails logo is yii framework logo, isn't it?

### ISSUE THREAD

**Issue by cybercarnage** [mkrl/misbrands#63]

**Comment by dimitrisnl** [comment]
It's the (old?) Wordpress logo

<img width="310" alt="Screen Shot 2022-01-25 at 11 24 02 AM" src="https://user-images.githubusercontent.com/4951004/150949037-e1f8fd29-b4f5-4270-a69e-8196acda6f71.png">

**Comment by cybercarnage** [comment]
exactly
