### ISSUE TITLE
react logo it's not correct !!! it's of svelte 

### ISSUE THREAD

**Issue by notpushkin** [mkrl/misbrands#70]
s

**Comment by AdamFrack** [comment]
![thepoint](https://github.com/mkrl/misbrands/assets/147642132/960cddc5-04cd-4622-b376-b31ab1b222e1)

**Comment by ghost** [comment]
![thepoint](https://github.com/mkrl/misbrands/assets/147642132/b078be65-f5e0-459a-96ac-000fd4ef390f)

**Comment by notpushkin** [comment]
Yeah, sorry, I was trying to make a joke. I didn't realize Svelte logo [does indeed really look like this](https://github.com/mkrl/misbrands/assets/1298948/ec2260cd-69d4-477e-ae32-8de4c0e16231) :^(

<details>
<summary>on a serious note</summary>

For those still wondering, the point is that Misbrands version uses Angular logo, not Svelte (which looks completely different). This joke is a bit low effort on my part and not really obvious, I agree.

</details>
